### ISSUE TITLE
Déontologie du datascientist sur les données Covid

### ISSUE THREAD

**Issue by RLesur** [spyrales/la-piscine#6]
L'objectif de la piscine est très clair : faire en sorte que les personnes manipulent des vraies données pour mettre en oeuvre ce qu'elles apprennent.  
Cependant, je pense qu'il faudra faire un peu attention à la communication autour des réalisations sur les données Covid.  
Je partage l'avis de l'article suivant qui, en substance, recommande de ne pas créer de "bruit" en ce moment sur ce sujet https://correlaid.org/en/blog/data-scientists-during-covid/

**Comment by strainel** [comment]
Oui suis bien d'accord... on lit beaucoup (trop) de choses sur le sujet en ce moment.
L'idée est de partager entre "nous" les réalisations et susciter des idées.
Il faudra peut-être mettre un message pour dire que ce sont des exercices.
