### ISSUE TITLE
readme.md : que fait-on de la branche ?

### ISSUE THREAD

**Issue by Welsh44** [spyrales/la-piscine#8]
La partie du readme sur le vestiaire est parfaite.
Juste une question à laquelle on ne répond pas : que devient ma branche ? Faut-il la détruire ? Est-elle mergée automatiquement quand la PR est acceptée? ....

Et je suis désolé mais je ne sais pas... :-(

**Comment by RLesur** [comment]
C'est vrai : c'est à chacun de décider. En général, on la supprime car il n'y a pas d'intérêt à la garder une fois la PR acceptée.

**Comment by strainel** [comment]
Je vais ajouter un complément pour indiquer que la branche se sert plus & qu'elle peut être supprimée.
